# Generated by Django 4.2.4 on 2023-11-15 15:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=15)),
                ('schedule_date', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Agendado'), (2, 'Finalizado'), (3, 'Cancelado')], default=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='professional.professional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'scheduler',
            },
        ),
    ]
