# Generated by Django 4.2.4 on 2023-11-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='service_ids',
            new_name='services',
        ),
    ]
