# Generated by Django 4.2.4 on 2023-11-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='customer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='customer_phone',
            field=models.CharField(max_length=15),
        ),
    ]
