# Generated by Django 4.2.4 on 2023-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Agendado'), (2, 'Finalizado'), (3, 'Cancelado')], default=1, verbose_name='Status'),
        ),
    ]
