# Generated by Django 4.2.4 on 2023-11-11 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(blank=True, max_length=100, null=True, verbose_name='Negócio')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('interval', models.IntegerField(default=30, verbose_name='Intervalo')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('profile_image_path', models.CharField(blank=True, max_length=250, null=True, verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'db_table': 'professional',
            },
        ),
        migrations.CreateModel(
            name='WorkingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(verbose_name='Dia da semana')),
                ('start_time', models.CharField(verbose_name='Hora de início')),
                ('end_time', models.CharField(verbose_name='Hora de término')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_plans', to='professional.professional')),
            ],
            options={
                'verbose_name': 'Plano de trabalho',
                'verbose_name_plural': 'Planos de trabalho',
                'db_table': 'working_plan',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('time', models.TimeField(verbose_name='Tempo')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='professional.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.CharField(verbose_name='Hora de início')),
                ('end_time', models.CharField(verbose_name='Hora de término')),
                ('working_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_time', to='professional.workingplan')),
            ],
            options={
                'verbose_name': 'Horário de pausa',
                'verbose_name_plural': 'Horários de pausa',
                'db_table': 'break_time',
            },
        ),
    ]
