# Generated by Django 4.2.4 on 2023-11-22 16:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_hour', to='professional.professional', verbose_name='Profissional')),
            ],
        ),
    ]
