# Generated by Django 4.2.4 on 2023-11-02 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktime',
            name='working_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_time', to='professional.workingplan'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterModelTable(
            name='breaktime',
            table='break_time',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
