# Generated by Django 4.2.4 on 2023-11-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_blockhour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockhour',
            old_name='times',
            new_name='hours',
        ),
    ]
