# Generated by Django 4.2.4 on 2023-11-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_alter_breaktime_working_plan_alter_professional_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='professional.professional', verbose_name='Profissional'),
        ),
    ]
