# Generated by Django 4.2.4 on 2023-11-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_rename_times_blockhour_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockhour',
            options={'verbose_name': 'Horário bloqueado', 'verbose_name_plural': 'Horários bloqueados'},
        ),
        migrations.AlterModelTable(
            name='blockhour',
            table='block_hour',
        ),
    ]
