# Generated by Django 4.2.4 on 2023-11-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_alter_service_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('service_ids', models.JSONField()),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('customer_phone', models.CharField(db_index=True, max_length=255)),
                ('schedule_date', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='professional.professional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'scheduling',
            },
        ),
    ]
