# Generated by Django 4.2.4 on 2023-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktime',
            name='end_time',
            field=models.CharField(verbose_name='Hora de término'),
        ),
        migrations.AlterField(
            model_name='breaktime',
            name='start_time',
            field=models.CharField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='workingplan',
            name='end_time',
            field=models.CharField(verbose_name='Hora de término'),
        ),
        migrations.AlterField(
            model_name='workingplan',
            name='start_time',
            field=models.CharField(verbose_name='Hora de início'),
        ),
    ]
