# Generated by Django 4.2.4 on 2023-11-25 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_alter_blockhour_options_alter_blockhour_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='professional.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
                'db_table': 'vacation',
                'ordering': ['start_date'],
            },
        ),
    ]
