# Generated by Django 4.2.4 on 2023-11-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0005_alter_breaktime_end_time_alter_breaktime_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduling',
        ),
    ]
